import React from 'react';
import { 
  Users, 
  Clock, 
  MapPin, 
  ChevronRight, 
  Plus, 
  Coffee, 
  Building2, 
  Landmark, 
  Stethoscope,
  MoreHorizontal,
  LogOut,
  LayoutDashboard,
  QrCode,
  Bell,
  Play,
  Pause,
  XCircle,
  TrendingUp,
  Brain,
  Car,
  FileText,
  MessageCircle,
  Smartphone,
  ArrowRightLeft,
  Zap,
  BarChart2,
  PieChart
} from 'lucide-react';

export const Icons = {
  Users,
  Clock,
  MapPin,
  ChevronRight,
  Plus,
  Coffee,
  Building: Building2,
  Bank: Landmark,
  Hospital: Stethoscope,
  Temple: Landmark, // Reusing Landmark for Temple
  RTO: Car,
  Aadhaar: FileText,
  More: MoreHorizontal,
  Logout: LogOut,
  Dashboard: LayoutDashboard,
  QrCode,
  Bell,
  Play,
  Pause,
  Close: XCircle,
  Trending: TrendingUp,
  AI: Brain,
  WhatsApp: MessageCircle,
  SMS: Smartphone,
  Smartphone,
  Exchange: ArrowRightLeft,
  Zap,
  BarChart: BarChart2,
  PieChart
};